version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bot
  bot:
    build:
      context: docker/node
    env_file:
      - .env
      - .env.private
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: [ "node", "/app/bin/bot.js" ]
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local